version: '3.9'
services:
  # Bases de données MySQL
  customer-database:
    image: mysql:latest
    container_name: customer-database
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - pitstopnetwork

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - 5672:5672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - pitstopnetwork

  # Microservices backend
  customer-service:
    image: fatimaalzahra0412/customer-service:latest
    container_name: customer-service
    ports:
      - 3001:3001
    depends_on:
      - customer-database
      - rabbitmq
    networks:
      - pitstopnetwork

networks:
  pitstopnetwork:
     driver: bridge

volumes:
  mysql-data:
  rabbitmq-data: